### ISSUE TITLE
Contao 5.3 Support

### ISSUE THREAD

**Issue by jedoCodes** [Contao-DD/advanced-classes-bundle#16]
In Contao version 5.3 RC-3 the settings are no longer displayed

![Screenshot at Feb 11 07-26-16](https://github.com/Contao-DD/advanced-classes-bundle/assets/1821865/f0a67a7e-f0ff-4c52-8854-86a52ee36e05)

**Comment by MDevster** [comment]
Fixed in version 1.5.3

**Comment by fr4nk2342** [comment]
I wanted to create an additional set for Bootstrap5 because the xxl classes are missing in the set for Bootstrap4.

As described, I registered the set (copied the existing bootstrap4.json to avoid errors) and selected it in the settings.

But the selection is missing, as in the screenshot of @jedoCodes

**Comment by MDevster** [comment]
@fr4nk2342 pls send the file to support@pdir.de and we will add it to the extension. You can use this issue https://github.com/Contao-DD/advanced-classes-bundle/issues/18 for conversation on this topic.
